# Generated by Django 4.1.5 on 2023-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(max_length=20)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=50)),
                ('district', models.TextField()),
                ('branch', models.TextField()),
                ('accounttype', models.TextField()),
            ],
        ),
    ]
