# Generated by Django 4.1.5 on 2023-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='full_name',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
