# Generated by Django 4.1.5 on 2023-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_alter_details_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='full_name',
            field=models.TextField(max_length=20),
        ),
    ]
